name: HACS validation

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: hacs-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hacs:
    name: Validate with HACS
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Validate integration
        uses: hacs/action@main
        with:
          category: integration
